### ISSUE TITLE
fill_rect not filling on SSD1675 2.13" monochrome eInk display

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_EPD#16]
Using `fill_rect` on the 2.13" monochrome eInk breakout does not fill the drawn rectangle. Tested on two 2.13" monochrome displays, issue is present on both. Tested on all other eInk displays, issue is not present on any of the others.

![2_13_inch_eInk_fill_rect](https://user-images.githubusercontent.com/7865090/56603754-57125b80-65ce-11e9-8074-89606ec8f79a.jpg)

**Comment by dherrada** [comment]
I'll take a look at this and see if I may be able to fix it.

**Comment by mrmcwethy** [comment]
@kattni This may have been fixed by a change made recently in Adafruit_Circuitpython_EPD.  Unfortunately, I don't own that display, so if you have time, can you recheck this issue using release 2.03 of this library?

**Comment by kattni** [comment]
@mrmcwethy Hey! Welcome back! I tested this with the recent release of EPD and the issue is still present.

**Comment by kattni** [comment]
@dherrada Are you actively working on this? If not, please remove the self-assignment so others know it's not actively being worked on.

**Comment by mrmcwethy** [comment]
Thanks for trying. I was just hoping, cause it smelled like the same issue.  Oh well I was wrong.
Mike

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 17, 2019 at 3:50 PM, Kattni<notifications@github.com> wrote:   
@mrmcwethy Hey! Welcome back! I tested this with the recent release of EPD and the issue is still present.

**Comment by siddacious** [comment]
@kattni @dherrada mentioned to me recently that he's going on a trip for a while and not able to work on CP. I've unassigned him

**Comment by ladyada** [comment]
fixed here
https://github.com/adafruit/Adafruit_CircuitPython_EPD/pull/28/files#diff-b4cee2f79ac45ea5313660a184d9347c
